version: '3.9'
services:
  jupyter:
    command: >
      bash -c "echo Point browser to http://localhost:8888/lab?token=docker &&
      jupyter-lab --ip=0.0.0.0 --no-browser --allow-root"
    environment:
      - JUPYTER_TOKEN=docker
    image: daz502/dazboconda:latest
    ports:
      - 8888:8888
    volumes:
      - .:/opt/notebooks
